apiVersion: v1
kind: Service
metadata:
  name: loopr-exporter
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.exporter.port }}
      targetPort: {{ .Values.exporter.port }}
  selector:
    app: loopr-exporter
